schema_version = "1.1"

[task]
name = "LiteCoder/nginx-api-gateway-docker"
description = ""
authors = []
keywords = []

[metadata]
author_name = "generated"
author_email = "generated@harbor.ai"
difficulty = "medium"
category = "system-administration"
tags = [ "nginx", "docker-compose", "flask", "networking", "api-gateway",]
expert_time_estimate_min = 30.0
junior_time_estimate_min = 60.0

[verifier]
timeout_sec = 600.0

[agent]
timeout_sec = 3600.0

[environment]
docker_image = "hub.byted.org/dwn_open_docker/litecoder-terminal--nginx-api-gateway-docker:opencode-1.15.4-946871aa780a"
build_timeout_sec = 600.0
cpus = 2
memory_mb = 4096
storage_mb = 10240
gpus = 0
allow_internet = true
mcp_servers = []

[verifier.env]

[environment.env]

[solution.env]
