schema_version = "1.1"

[task]
name = "LiteCoder/extract-ssh-key-message"
description = ""
authors = []
keywords = []

[metadata]
author_name = "generated"
author_email = "generated@harbor.ai"
difficulty = "easy"
category = "security"
tags = [ "steganography", "python", "base64", "cryptography", "file-parsing",]
expert_time_estimate_min = 15.0
junior_time_estimate_min = 30.0

[verifier]
timeout_sec = 360.0

[agent]
timeout_sec = 1800.0

[environment]
docker_image = "hub.byted.org/dwn_open_docker/litecoder-terminal--extract-ssh-key-message:opencode-1.15.4-1d7e547c9eab"
build_timeout_sec = 600.0
cpus = 1
memory_mb = 2048
storage_mb = 10240
gpus = 0
allow_internet = true
mcp_servers = []

[verifier.env]

[environment.env]

[solution.env]
