schema_version = "1.1"

[task]
name = "LiteCoder/build-qemu-from-source"
description = ""
authors = []
keywords = []

[metadata]
author_name = "generated"
author_email = "generated@harbor.ai"
difficulty = "hard"
category = "system-administration"
tags = [ "qemu", "build-from-source", "c-compilation", "linux", "emulation",]
expert_time_estimate_min = 45.0
junior_time_estimate_min = 90.0

[verifier]
timeout_sec = 600.0

[agent]
timeout_sec = 3600.0

[environment]
docker_image = "hub.byted.org/dwn_open_docker/litecoder-terminal--build-qemu-from-source:opencode-1.15.4-4ab91f78943c"
build_timeout_sec = 600.0
cpus = 4
memory_mb = 8192
storage_mb = 20480
gpus = 0
allow_internet = true
mcp_servers = []

[verifier.env]

[environment.env]

[solution.env]
