schema_version = "1.1"

[task]
name = "LiteCoder/cpu-distilbert-sentiment-analysis"
description = ""
authors = []
keywords = []

[metadata]
author_name = "generated"
author_email = "generated@harbor.ai"
difficulty = "medium"
category = "machine-learning"
tags = [ "python", "pytorch", "transformers", "nlp", "sentiment-analysis",]
expert_time_estimate_min = 30.0
junior_time_estimate_min = 60.0

[verifier]
timeout_sec = 600.0

[agent]
timeout_sec = 3600.0

[environment]
docker_image = "hub.byted.org/dwn_open_docker/litecoder-terminal--cpu-distilbert-sentiment-analysis:opencode-1.15.4-6b7b932b3bee"
build_timeout_sec = 900.0
cpus = 2
memory_mb = 4096
storage_mb = 20480
gpus = 0
allow_internet = true
mcp_servers = []

[verifier.env]

[environment.env]

[solution.env]
