#!/bin/bash
# This script runs inside the Docker container to set up the forensic challenge.
set -e

SECRET_HEX="a3f1b9c7d4e60218f5a7b3c9d1e4f60789abcdef0123456789abcdef01234567"
PASSPHRASE="ProjectOrion2024!"

mkdir -p /app/sysbackup

# Create the secret file and password-protected zip archive
echo -n "$SECRET_HEX" > /tmp/product_key.txt
apt-get update && apt-get install -y zip unzip p7zip-full > /dev/null 2>&1
cd /tmp
zip -P "$PASSPHRASE" secret_archive.zip product_key.txt > /dev/null 2>&1

# Disguise the archive as a system log file in sysbackup
cp /tmp/secret_archive.zip /app/sysbackup/kern_module.cache

# Create realistic decoy files in sysbackup
echo "# System network configuration - generated by netplan" > /app/sysbackup/netplan.cfg
echo "network:" >> /app/sysbackup/netplan.cfg
echo "  version: 2" >> /app/sysbackup/netplan.cfg
echo "  ethernets:" >> /app/sysbackup/netplan.cfg
echo "    eth0:" >> /app/sysbackup/netplan.cfg
echo "      dhcp4: true" >> /app/sysbackup/netplan.cfg

cat > /app/sysbackup/sysctl_snapshot.conf <<'SYSCTL'
# Kernel sysctl configuration snapshot
net.ipv4.ip_forward = 0
net.ipv4.conf.all.send_redirects = 0
net.ipv4.conf.default.accept_source_route = 0
kernel.sysrq = 0
kernel.core_uses_pid = 1
net.ipv4.tcp_syncookies = 1
SYSCTL

cat > /app/sysbackup/cron_daily.bak <<'CRON'
# /etc/cron.daily backup - 2024-06-15
SHELL=/bin/sh
PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
0 3 * * * root /usr/sbin/logrotate /etc/logrotate.conf
30 4 * * 0 root /opt/scripts/weekly_cleanup.sh
CRON

cat > /app/sysbackup/grub.defaults <<'GRUB'
GRUB_DEFAULT=0
GRUB_TIMEOUT_STYLE=hidden
GRUB_TIMEOUT=0
GRUB_DISTRIBUTOR=`lsb_release -i -s 2> /dev/null || echo Debian`
GRUB_CMDLINE_LINUX_DEFAULT="quiet splash"
GRUB_CMDLINE_LINUX=""
GRUB

dd if=/dev/urandom of=/app/sysbackup/swap_partition.img bs=1024 count=8 2>/dev/null

cat > /app/sysbackup/fstab.snapshot <<'FSTAB'
# /etc/fstab snapshot - 2024-06-10
UUID=a1b2c3d4-e5f6-7890-abcd-ef1234567890 / ext4 errors=remount-ro 0 1
UUID=f9e8d7c6-b5a4-3210-fedc-ba9876543210 /home ext4 defaults 0 2
/swapfile none swap sw 0 0
FSTAB

# Create .bash_history with clues about the passphrase and archive
cat > /app/.bash_history <<'HISTORY'
ls -la /var/log/
sudo systemctl status nginx
cd /home/shared/projects
git log --oneline -5
cat README.md
echo "Starting backup for Project Orion"
cd /opt/sysbackup
ls -la
zip -P 'ProjectOrion2024!' secret_archive.zip product_key.txt
mv secret_archive.zip /opt/sysbackup/kern_module.cache
cp /opt/sysbackup/kern_module.cache /app/sysbackup/kern_module.cache
echo "backup complete, renamed to look like kernel cache"
history -c
sudo apt-get update
df -h
ping -c 3 google.com
cat /etc/hostname
whoami
exit
HISTORY

# Clean up temp files
rm -f /tmp/product_key.txt /tmp/secret_archive.zip

echo "Challenge environment setup complete."
