import os
import subprocess
import tarfile
import shutil
import glob


def test_autotools_files_exist():
    """Verify that essential autotools configuration files were created."""
    required_files = [
        'configure.ac',
        'Makefile.am',
        'libmini.pc.in'
    ]

    for file in required_files:
        assert os.path.isfile(file), f"Missing required autotools file: {file}"

    # Check for bootstrap or autogen.sh (at least one must exist)
    has_bootstrap = os.path.isfile('bootstrap') or os.path.isfile('autogen.sh')
    assert has_bootstrap, "Missing bootstrap/autogen.sh script"


def test_configure_ac_content():
    """Verify configure.ac has proper library metadata and configuration."""
    with open('configure.ac', 'r') as f:
        content = f.read()

    # Check for library name and version
    assert 'libmini' in content, "configure.ac must reference libmini"
    assert '1.0.0' in content, "configure.ac must specify version 1.0.0"

    # Check for essential autotools macros
    assert 'AC_INIT' in content, "configure.ac missing AC_INIT"
    assert 'AC_OUTPUT' in content or 'AC_CONFIG_FILES' in content, "configure.ac missing output configuration"

    # Check for libtool support
    assert 'LT_INIT' in content or 'AC_PROG_LIBTOOL' in content, "configure.ac missing libtool initialization"


def test_makefile_am_content():
    """Verify Makefile.am configures library build correctly."""
    with open('Makefile.am', 'r') as f:
        content = f.read()

    # Check for library target
    assert 'lib_LTLIBRARIES' in content or 'LTLIBRARIES' in content, "Makefile.am missing libtool library target"
    assert 'libmini' in content, "Makefile.am must reference libmini"

    # Check for header installation
    assert 'include_HEADERS' in content or 'HEADERS' in content, "Makefile.am missing header installation"

    # Check for pkg-config support
    assert 'pkgconfig' in content.lower(), "Makefile.am missing pkg-config support"


def test_pkgconfig_template():
    """Verify pkg-config template has required fields."""
    with open('libmini.pc.in', 'r') as f:
        content = f.read()

    # Check for essential pkg-config fields
    assert 'Name:' in content, "libmini.pc.in missing Name field"
    assert 'Version:' in content or '@VERSION@' in content, "libmini.pc.in missing Version field"
    assert 'Libs:' in content, "libmini.pc.in missing Libs field"
    assert 'Cflags:' in content, "libmini.pc.in missing Cflags field"

    # Check that it references libmini
    assert 'libmini' in content or 'mini' in content, "libmini.pc.in must reference the library"


def test_bootstrap_workflow():
    """Test that bootstrap/autogen generates configure script."""
    # Find bootstrap script
    bootstrap_script = None
    if os.path.isfile('bootstrap') and os.access('bootstrap', os.X_OK):
        bootstrap_script = './bootstrap'
    elif os.path.isfile('autogen.sh') and os.access('autogen.sh', os.X_OK):
        bootstrap_script = './autogen.sh'

    assert bootstrap_script is not None, "No executable bootstrap/autogen.sh script found"

    # Run bootstrap
    result = subprocess.run([bootstrap_script], capture_output=True, text=True)
    assert result.returncode == 0, f"Bootstrap failed: {result.stderr}"

    # Verify configure was generated
    assert os.path.isfile('configure'), "configure script not generated by bootstrap"
    assert os.access('configure', os.X_OK), "configure script is not executable"


def test_configure_and_build():
    """Test that configure and make work correctly."""
    # Run configure
    result = subprocess.run(['./configure', '--prefix=/tmp/test-install'],
                          capture_output=True, text=True)
    assert result.returncode == 0, f"Configure failed: {result.stderr}"

    # Verify Makefile was generated
    assert os.path.isfile('Makefile'), "Makefile not generated by configure"

    # Run make
    result = subprocess.run(['make'], capture_output=True, text=True)
    assert result.returncode == 0, f"Make failed: {result.stderr}"

    # Check that library files were built (look for .la or .so files)
    la_files = glob.glob('*.la') + glob.glob('.libs/*.la')
    so_files = glob.glob('*.so*') + glob.glob('.libs/*.so*')
    a_files = glob.glob('*.a') + glob.glob('.libs/*.a')

    assert len(la_files) > 0 or len(so_files) > 0, "No library files built"


def test_make_check():
    """Test that make check runs successfully."""
    result = subprocess.run(['make', 'check'], capture_output=True, text=True)
    assert result.returncode == 0, f"make check failed: {result.stderr}"


def test_make_install():
    """Test that make install creates all required artifacts."""
    install_prefix = '/tmp/test-install'

    # Clean previous installation
    if os.path.exists(install_prefix):
        shutil.rmtree(install_prefix)

    # Run make install
    result = subprocess.run(['make', 'install'], capture_output=True, text=True)
    assert result.returncode == 0, f"make install failed: {result.stderr}"

    # Check for shared library (various naming conventions)
    lib_dir = os.path.join(install_prefix, 'lib')
    assert os.path.isdir(lib_dir), f"Library directory not created: {lib_dir}"

    so_files = glob.glob(os.path.join(lib_dir, 'libmini.so*'))
    assert len(so_files) > 0, f"Shared library not installed in {lib_dir}"

    # Check for static library
    static_lib = os.path.join(lib_dir, 'libmini.a')
    assert os.path.isfile(static_lib), f"Static library not installed: {static_lib}"

    # Check for header file
    include_dir = os.path.join(install_prefix, 'include')
    header_file = os.path.join(include_dir, 'mini.h')
    assert os.path.isfile(header_file), f"Header file not installed: {header_file}"

    # Check for pkg-config file
    pkgconfig_dir = os.path.join(lib_dir, 'pkgconfig')
    pc_file = os.path.join(pkgconfig_dir, 'libmini.pc')
    assert os.path.isfile(pc_file), f"pkg-config file not installed: {pc_file}"


def test_pkgconfig_functionality():
    """Test that pkg-config file works for downstream compilation."""
    install_prefix = '/tmp/test-install'
    lib_dir = os.path.join(install_prefix, 'lib')
    pkgconfig_dir = os.path.join(lib_dir, 'pkgconfig')

    # Set PKG_CONFIG_PATH
    env = os.environ.copy()
    env['PKG_CONFIG_PATH'] = pkgconfig_dir

    # Test pkg-config --cflags
    result = subprocess.run(['pkg-config', '--cflags', 'libmini'],
                          capture_output=True, text=True, env=env)
    assert result.returncode == 0, "pkg-config --cflags failed"
    assert '-I' in result.stdout, "pkg-config --cflags doesn't include -I flag"

    # Test pkg-config --libs
    result = subprocess.run(['pkg-config', '--libs', 'libmini'],
                          capture_output=True, text=True, env=env)
    assert result.returncode == 0, "pkg-config --libs failed"
    assert '-lmini' in result.stdout, "pkg-config --libs doesn't include -lmini"

    # Create a test program
    test_program = '/tmp/test_downstream.c'
    with open(test_program, 'w') as f:
        f.write('''
#include <mini.h>
#include <stdio.h>

int main(void) {
    int result = mini_add(10, 20);
    printf("Result: %d\\n", result);
    return (result == 30) ? 0 : 1;
}
''')

    # Compile using pkg-config
    result = subprocess.run(
        ['sh', '-c', f'gcc {test_program} $(pkg-config --cflags --libs libmini) -o /tmp/test_downstream'],
        capture_output=True, text=True, env=env
    )
    assert result.returncode == 0, f"Compilation with pkg-config failed: {result.stderr}"

    # Run the compiled program
    result = subprocess.run(['/tmp/test_downstream'], capture_output=True, text=True, env=env)
    assert result.returncode == 0, "Test program execution failed"
    assert 'Result: 30' in result.stdout, "Test program produced incorrect output"


def test_make_dist():
    """Test that make dist creates a proper distribution tarball."""
    result = subprocess.run(['make', 'dist'], capture_output=True, text=True)
    assert result.returncode == 0, f"make dist failed: {result.stderr}"

    # Check for tarball
    tarball = 'libmini-1.0.0.tar.gz'
    assert os.path.isfile(tarball), f"Distribution tarball not created: {tarball}"

    # Verify tarball is valid and contains essential files
    with tarfile.open(tarball, 'r:gz') as tar:
        members = tar.getnames()

        # Check for essential files in tarball
        has_configure = any('configure' in m for m in members)
        has_makefile_in = any('Makefile.in' in m for m in members)
        has_source = any('mini.c' in m for m in members)
        has_header = any('mini.h' in m for m in members)

        assert has_configure, "Tarball missing configure script"
        assert has_makefile_in, "Tarball missing Makefile.in"
        assert has_source, "Tarball missing source files"
        assert has_header, "Tarball missing header files"


def test_tarball_rebuild():
    """Test that the distribution tarball can be extracted and rebuilt."""
    tarball = 'libmini-1.0.0.tar.gz'
    extract_dir = '/tmp/tarball-test'

    # Clean and create extraction directory
    if os.path.exists(extract_dir):
        shutil.rmtree(extract_dir)
    os.makedirs(extract_dir)

    # Extract tarball
    with tarfile.open(tarball, 'r:gz') as tar:
        tar.extractall(extract_dir)

    # Find the extracted directory
    extracted_dirs = [d for d in os.listdir(extract_dir) if os.path.isdir(os.path.join(extract_dir, d))]
    assert len(extracted_dirs) > 0, "No directory found in extracted tarball"

    build_dir = os.path.join(extract_dir, extracted_dirs[0])

    # Try to build from extracted tarball
    result = subprocess.run(['./configure', '--prefix=/tmp/tarball-install'],
                          cwd=build_dir, capture_output=True, text=True)
    assert result.returncode == 0, f"Configure from tarball failed: {result.stderr}"

    result = subprocess.run(['make'], cwd=build_dir, capture_output=True, text=True)
    assert result.returncode == 0, f"Make from tarball failed: {result.stderr}"


def test_library_soname():
    """Verify that shared library has proper soname versioning."""
    install_prefix = '/tmp/test-install'
    lib_dir = os.path.join(install_prefix, 'lib')

    # Find shared library files
    so_files = glob.glob(os.path.join(lib_dir, 'libmini.so*'))
    assert len(so_files) > 0, "No shared library files found"

    # At least one should be a symlink or versioned file
    has_versioned = any('.so.' in f for f in so_files)
    assert has_versioned or len(so_files) >= 1, "Shared library missing proper versioning"


def test_clean_targets():
    """Test that clean and distclean targets work."""
    # Test clean
    result = subprocess.run(['make', 'clean'], capture_output=True, text=True)
    assert result.returncode == 0, f"make clean failed: {result.stderr}"

    # Test distclean
    result = subprocess.run(['make', 'distclean'], capture_output=True, text=True)
    assert result.returncode == 0, f"make distclean failed: {result.stderr}"

    # After distclean, Makefile should be removed
    assert not os.path.isfile('Makefile'), "Makefile still exists after distclean"


def test_configure_prefix_option():
    """Test that configure accepts --prefix option."""
    # Reconfigure if needed
    if not os.path.isfile('configure'):
        if os.path.isfile('bootstrap'):
            subprocess.run(['./bootstrap'], capture_output=True)
        elif os.path.isfile('autogen.sh'):
            subprocess.run(['./autogen.sh'], capture_output=True)

    result = subprocess.run(['./configure', '--prefix=/tmp/custom-prefix'],
                          capture_output=True, text=True)
    assert result.returncode == 0, "configure --prefix failed"


def test_library_linkable():
    """Test that the installed library can actually be linked against."""
    install_prefix = '/tmp/test-install'
    lib_dir = os.path.join(install_prefix, 'lib')
    include_dir = os.path.join(install_prefix, 'include')

    # Create a simple test program
    test_source = '/tmp/link_test.c'
    with open(test_source, 'w') as f:
        f.write('''
#include <mini.h>
#include <stdio.h>

int main(void) {
    int sum = mini_add(5, 7);
    int product = mini_multiply(3, 4);
    printf("Sum: %d, Product: %d\\n", sum, product);
    return (sum == 12 && product == 12) ? 0 : 1;
}
''')

    # Try to compile and link
    result = subprocess.run([
        'gcc', test_source,
        f'-I{include_dir}',
        f'-L{lib_dir}',
        '-lmini',
        '-o', '/tmp/link_test'
    ], capture_output=True, text=True)

    assert result.returncode == 0, f"Failed to link against installed library: {result.stderr}"

    # Run the test program
    env = os.environ.copy()
    env['LD_LIBRARY_PATH'] = lib_dir
    result = subprocess.run(['/tmp/link_test'], capture_output=True, text=True, env=env)
    assert result.returncode == 0, "Linked test program failed to execute correctly"
    assert 'Sum: 12' in result.stdout, "Test program produced incorrect output"


def test_static_library_linkable():
    """Test that static library can be linked."""
    install_prefix = '/tmp/test-install'
    lib_dir = os.path.join(install_prefix, 'lib')
    include_dir = os.path.join(install_prefix, 'include')
    static_lib = os.path.join(lib_dir, 'libmini.a')

    # Create a simple test program
    test_source = '/tmp/static_link_test.c'
    with open(test_source, 'w') as f:
        f.write('''
#include <mini.h>

int main(void) {
    return mini_multiply(2, 3) == 6 ? 0 : 1;
}
''')

    # Compile with static library
    result = subprocess.run([
        'gcc', test_source,
        f'-I{include_dir}',
        static_lib,
        '-o', '/tmp/static_link_test'
    ], capture_output=True, text=True)

    assert result.returncode == 0, f"Failed to link against static library: {result.stderr}"

    # Run the test program
    result = subprocess.run(['/tmp/static_link_test'], capture_output=True, text=True)
    assert result.returncode == 0, "Static linked program failed"


def test_no_hardcoded_outputs():
    """Ensure the solution doesn't just copy pre-built files."""
    # Check that configure.ac is not a binary or suspiciously small
    assert os.path.getsize('configure.ac') > 100, "configure.ac is suspiciously small"

    # Check that Makefile.am is not trivial
    assert os.path.getsize('Makefile.am') > 50, "Makefile.am is suspiciously small"

    # Verify configure script was actually generated (should be large)
    if os.path.isfile('configure'):
        assert os.path.getsize('configure') > 10000, "configure script seems invalid (too small)"
