schema_version = "1.1"

[task]
name = "LiteCoder/sample_0001_254510e4"
description = ""
authors = []
keywords = []

[metadata]
author_name = "generated"
author_email = "generated@harbor.ai"
difficulty = "easy"
category = "system-administration"
tags = [ "git", "version-control", "file-recovery", "bash",]
expert_time_estimate_min = 5.0
junior_time_estimate_min = 15.0

[verifier]
timeout_sec = 360.0

[agent]
timeout_sec = 1800.0

[environment]
docker_image = "hub.byted.org/dwn_open_docker/litecoder-terminal--sample_0001_254510e4:opencode-1.15.4-32312b5c5227"
build_timeout_sec = 600.0
cpus = 1
memory_mb = 2048
storage_mb = 10240
gpus = 0
allow_internet = true
mcp_servers = []

[verifier.env]

[environment.env]

[solution.env]
