schema_version = "1.1"

[task]
name = "LiteCoder/build-cpu-pytorch-mkl-wheel"
description = ""
authors = []
keywords = []

[metadata]
author_name = "generated"
author_email = "generated@harbor.ai"
difficulty = "hard"
category = "machine-learning"
tags = [ "pytorch", "build-from-source", "intel-mkl", "cmake", "python",]
expert_time_estimate_min = 60.0
junior_time_estimate_min = 150.0

[verifier]
timeout_sec = 600.0

[agent]
timeout_sec = 3600.0

[environment]
docker_image = "hub.byted.org/dwn_open_docker/litecoder-terminal--build-cpu-pytorch-mkl-wheel:opencode-1.15.4-12120d02cbb2"
build_timeout_sec = 600.0
cpus = 4
memory_mb = 8192
storage_mb = 20480
gpus = 0
allow_internet = true
mcp_servers = []

[verifier.env]

[environment.env]

[solution.env]
