#!/usr/bin/env python3
"""
Custom file encryption tool.
Encrypts files using XOR with a keystream generated by Python's random module.
The seed is derived from the file's size in bytes at the time of encryption.
"""

import random
import sys
import os
import json
import hashlib


def encrypt_file(input_path, output_path):
    """Encrypt a single file using XOR with a PRNG-based keystream."""
    with open(input_path, 'rb') as f:
        plaintext = f.read()

    original_size = len(plaintext)

    # Seed the RNG with the original file size
    random.seed(original_size)

    # Generate keystream and XOR
    ciphertext = bytes([b ^ random.randint(0, 255) for b in plaintext])

    with open(output_path, 'wb') as f:
        f.write(ciphertext)

    # Compute SHA-256 of original
    sha256_hash = hashlib.sha256(plaintext).hexdigest()

    return {
        "original_name": os.path.basename(input_path),
        "encrypted_name": os.path.basename(output_path),
        "original_size": original_size,
        "sha256_original": sha256_hash
    }


def main():
    if len(sys.argv) < 3:
        print("Usage: encryptor.py <input_dir> <output_dir>")
        sys.exit(1)

    input_dir = sys.argv[1]
    output_dir = sys.argv[2]
    os.makedirs(output_dir, exist_ok=True)

    manifest = {"files": []}

    for filename in sorted(os.listdir(input_dir)):
        filepath = os.path.join(input_dir, filename)
        if os.path.isfile(filepath) and not filename.endswith('.enc'):
            base, ext = os.path.splitext(filename)
            enc_name = base + '.enc'
            enc_path = os.path.join(output_dir, enc_name)
            info = encrypt_file(filepath, enc_path)
            manifest["files"].append(info)
            print(f"Encrypted {filename} -> {enc_name}")

    manifest_path = os.path.join(output_dir, "manifest.json")
    with open(manifest_path, 'w') as f:
        json.dump(manifest, f, indent=2)
    print(f"Manifest written to {manifest_path}")


if __name__ == "__main__":
    main()
