schema_version = "1.1"

[task]
name = "LiteCoder/fix-broken-build-system"
description = ""
authors = []
keywords = []

[metadata]
author_name = "generated"
author_email = "generated@harbor.ai"
difficulty = "medium"
category = "software-engineering"
tags = [ "cmake", "c++", "c", "build-systems", "debugging",]
expert_time_estimate_min = 25.0
junior_time_estimate_min = 60.0

[verifier]
timeout_sec = 600.0

[agent]
timeout_sec = 2700.0

[environment]
docker_image = "hub.byted.org/dwn_open_docker/litecoder-terminal--fix-broken-build-system:opencode-1.15.4-e0e436817b99"
build_timeout_sec = 600.0
cpus = 2
memory_mb = 4096
storage_mb = 10240
gpus = 0
allow_internet = true
mcp_servers = []

[verifier.env]

[environment.env]

[solution.env]
