schema_version = "1.1"

[task]
name = "LiteCoder/ssh-mfa-google-authenticator"
description = ""
authors = []
keywords = []

[metadata]
author_name = "generated"
author_email = "generated@harbor.ai"
difficulty = "medium"
category = "system-administration"
tags = [ "ssh", "pam", "mfa", "google-authenticator", "linux",]
expert_time_estimate_min = 20.0
junior_time_estimate_min = 45.0

[verifier]
timeout_sec = 360.0

[agent]
timeout_sec = 2700.0

[environment]
docker_image = "hub.byted.org/dwn_open_docker/litecoder-terminal--ssh-mfa-google-authenticator:opencode-1.15.4-2398cc6b5630"
build_timeout_sec = 600.0
cpus = 1
memory_mb = 2048
storage_mb = 10240
gpus = 0
allow_internet = true
mcp_servers = []

[verifier.env]

[environment.env]

[solution.env]
